# Generated by Django 3.0.8 on 2020-10-17 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demomodel',
            name='date',
        ),
        migrations.RemoveField(
            model_name='demomodel',
            name='profile_pic',
        ),
        migrations.AlterField(
            model_name='demomodel',
            name='id',
            field=models.AutoField(auto_created=True, default=True, primary_key=True, serialize=False, unique=True),
        ),
    ]
