# Generated by Django 3.0.8 on 2020-10-17 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20201017_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='demomodel',
            name='profile_pic',
            field=models.ImageField(default=True, max_length=1024, upload_to='img/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='demomodel',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
